stages:
- lint
clang:
  stage: lint
  image: alpine:latest
  before_script:
    - apk add --no-cache clang git
  script:
    - |
      FILES=$(find . \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \))
      echo "Changed files:"
      echo "$FILES"
      for file in $FILES; do
        clang-format "$file" | diff -u "$file" - || exit 1
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
