stages:
  - lint
clang:
  stage: lint
  image: registry.anorlondo.dev/anorlondo/build-images/alpine:3.23
  before_script:
    - apk add --no-cache clang clang-extra-tools git
  script:
    - |
      FILES=$(find . \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \))
      for file in $FILES; do
        clang-format "$file" | diff -u "$file" - || exit 1
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
